---
- name: Clear Archive Logs
  hosts: all
  gather_facts: false
  tasks:
    - name: Clear Archive Logs in C:\Windows\System32\winevt\Logs
      win_command: wevtutil.exe cl "{{ item }}"
      loop:
        - C:\Windows\System32\winevt\Logs\Application.evtx
        - C:\Windows\System32\winevt\Logs\Security.evtx
        - C:\Windows\System32\winevt\Logs\System.evtx
      when: "'Archive' in item"
