- name: Run PowerShell script from a specific location
  hosts: all
  gather_facts: false
  tasks:
    - name: Change directory to script location
      win_shell: cd C:\

    - name: Run PowerShell script
      win_shell: .\archive.ps1
