- name: Clear archive files in specific folder
  hosts: all
  become: yes
  become_user: training
  become_password: Training1!
  gather_facts: no

  tasks:
  - name: Remove archive files
    win_file:
      path: 'c:\windows\system32\winevt\logs'
      state: absent
      recurse: no
      patterns: "archive*.*"
