- name: Delete archived Application event log
  hosts: all

  tasks:
    - name: Delete archived Application event log
      win_shell: wevtutil cl "c:\windows\System32\Winevt\Logs"
      become: true
      vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_user: training
        ansible_become_password: Training1!
        ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
