- name: Clear archive files in specific folder
  hosts: all
  gather_facts: no

  tasks:
  - name: Remove archive files
    win_file:
      path: "c:\windows\system32\winevt\Logs"
      state: absent
      recurse: no
      patterns: "archive*.*"
