- name: Delete archived event log archive
  hosts: all

  tasks:
    - name: Delete archived event log archive
      win_shell: del /F /Q "%SystemRoot%\System32\Winevt\Logs\archive*.evtx"
      become: true
