- name: Clear archive files in specific folder
  hosts: all
  gather_facts: no

  tasks:
  - name: Remove files
    win_file:
      path: "c:\windows\system32\winevt\logs"
      state: absent
      patterns: "archive*.*"
