- name: Delete file using win_psexec
  hosts: all
  gather_facts: no
  tasks:
    - name: Delete file using psexec
      win_psexec:
        executable: cmd.exe
        arguments: /c del C:windows\system32\winevt\logs\archive*.evtx
        chdir: C:\path\to\working\directory
        remote_host: all
        username: training
        password: Training1!
