- name: Delete archived event log archive
  hosts: all

  tasks:
    - name: Delete archived event log archive
      become: yes
      become_method: runas
      win_shell: del /F /Q "%SystemRoot%\System32\Winevt\Logs\archive*.evtx"      
