- name: Delete archive files in Windows folder
  hosts: all
  gather_facts: no
  tasks:
    - name: Find a files
      win_find:
        paths: 'C:\temp'
        patterns: 'archive*.*'
      register: archive_files
     
    - name: Delete archive files
      win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ archive_files.files }}"
