- name: Delete archive files using PowerShell
  hosts: all
  gather_facts: no
  tasks:
    - name: Copy PowerShell script to remote machine
      win_copy:
        src: '\\172.16.25.22\c$\users\training\desktop'
        dest: 'c:\windows\system32\winevt\logs'
        remote_src: yes  
      become: yes
      become_user: administrator

    - name: Run PowerShell script to delete archive files
      win_shell: powershell.exe -ExecutionPolicy Bypass -File C:\\172.16.25.22\c\users\training\desktop\archive.ps1
