---
- name: Delete BMP files in Windows folder
  hosts: all
  gather_facts: no
  tasks:
    - name: Find BMP files
      win_find:
        paths: 'C:\windows\system32\winevt\logs'
        size: 17mb
      register: bmp_files
      become: true
      become_user: administrator
      become_method: runas

    - name: Delete BMP files
      win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ bmp_files.files }}"
