---
- name: Copy and move files starting with 'archive'
  hosts: all
  become: true
  gather_facts: false

  vars:
    source_directory: 'c:\windows\system32\winevt\logs\'
    destination_directory: 'c:\windows\temp\'

  tasks:
  - name: Copy files starting with 'archive' to destination
    win_copy:
      src: "{{ source_directory }}\\archive*"
      dest: "{{ destination_directory }}"
    register: copy_result
    vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_user: training
        ansible_become_password: Training1!
        ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only

  - name: Delete copied files from source
    win_file:
      path: "{{ source_directory }}\\archive*"
      state: absent
    when: copy_result.changed
