- name: Delete archived evtx files in event logs
  hosts: windows
  tasks:
  - name: Delete archived evtx files
    win_file:
      path: C:\Windows\System32\winevt\Logs\
      patterns: "archive*.evtx"
      recurse: yes
      state: absent
    vars:
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: training
      ansible_become_password: Training1!
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
