- name: Copy archive files and delete them
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Copy archive files to temp directory
      win_copy:
        src: "c:/windows/system32/winevt/logs/archive*"
        dest: "c:/windows/temp/"
      register: copy_result

    - name: Delete copied files
      win_shell: "wevtutil cl {{ item.path }}"
      loop: "{{ copy_result.files }}"
