- name: Delete archive files in Windows folder
  hosts: all
  gather_facts: no
  tasks:
    - name: Find a files
      win_file:
        path: 'C:\windows\system32\winevt\logs'
        pattern: 'archive'
        state: absent
