---
- name: Delete BMP files in Windows folder
  hosts: all
  gather_facts: no
  tasks:
    - name: Find BMP files
      win_find:
        paths: 'C:\temp'
        patterns: '*.bmp'
      register: bmp_files

    - name: Delete BMP files
      win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ bmp_files.files }}"
