---
- name: Ansible Find Example
  hosts: all
  tasks:
   - name : Find files
     become: yes
     win_find:
       paths: c:\windows\system32\winevt\logs
       patterns: archive*.*.evtx'
     register: output
   - name: Delete the files matching
     become: yes
     file:
       path: "{{item.path}}"
       state: absent
     with_items: "{{ output.files }}"
