- name: Delete archive files in Windows folder
  hosts: all
  gather_facts: no
  tasks:
    - name: Find a files
      win_find:
        paths: 'C:\windows\system32\winevt\logs'
        patterns: 'archive'
      register: archive_files
      vars:
        ansible_become_user: training
        ansible_become_password: Training1!  

    - name: Delete BMP files
      win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ archive_files.files }}"
