---
- name: Delete file in specific folder
  hosts: localhost
  become: true

  vars:
    folder_path: "c:\windows\system32\winevt\logs"
    file_name: "archive*.*.evtx"

  tasks:
    - name: Delete file
      file:
        path: "{{ folder_path }}/{{ file_name }}"
        state: absent
