---
- name: Copy file and run PowerShell script
  hosts: all
  gather_facts: false
  tasks:
    - name: Copy file to destination folder
      win_copy:
        src: \\172.16.25.22\c$\archive.ps1
        dest: C:\temp\archive.ps1
        remote_src: yes
      vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_user: training
        ansible_become_password: Training1!
        ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only


    - name: Run PowerShell script
      win_shell: |
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\temp\archive.ps1
