---
- name: Copy and Run Script on Windows Server
  hosts: all
  gather_facts: false
  vars:
    script_name: archive.ps1
    remote_source_path: \\172.16.25.22\c$\archive.ps1
    destination_path: C:\temp\{{ script_name }}
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: training
    ansible_become_password: Training1!
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    

  tasks:
    - name: Copy Script to Destination Server
      win_copy:
        src: "{{ remote_source_path }}/{{ script_name }}"
        dest: "{{ destination_path }}"
        remote_src: yes
      register: script_copy

    - name: Run Script on Destination Server
      win_shell: powershell.exe -ExecutionPolicy Bypass "{{ destination_path }}"
      when: script_copy.changed

    - name: Delete Script from Destination Server
      win_file:
        path: "{{ destination_path }}"
        state: absent
      when: script_copy.changed
