---
- name: Copy and Run Script on Windows Server
  hosts: all
  gather_facts: false
  vars:
    script_name: archive.ps1
    source_path: \\172.16.25.22\c$\archive.ps1{{ script_name }}
    destination_path: C:\temp\archive.ps1{{ script_name }}

  tasks:
    - name: Copy Script to Destination Server
      win_copy:
        src: "{{ \\172.16.25.22\c$\archive.ps1 }}"
        dest: "{{ C:\temp\archive.ps1 }}"
      register: script_copy

    - name: Run Script on Destination Server
      win_shell: powershell.exe -ExecutionPolicy Bypass "{{ C:\temp\archive.ps1 }}"
      when: script_copy.changed

    - name: Delete Script from Destination Server
      win_file:
        path: "{{ C:\temp\archive.ps1 }}"
        state: absent
      when: script_copy.changed
