- name: Delete archive files in Windows folder
  hosts: all
  gather_facts: no
  tasks:
    - name: Find a files
      win_file:
        paths: 'C:\windows\system32\winevt\logs\archive*.*.evtx'
        state: absent
