- name: Copy folder from remote to destination
  hosts: all
  tasks:
    - name: Copy folder
      win_copy:
        src: '\\172.16.25.22\c$\archive.ps1'
        dest: 'C:\temp'
        remote_src: yes
          
    - name: run script
      win_shell: C:\temp\archive.ps1
      register: result
