---
- name: Copy and move files starting with 'archive'
  hosts: all
  become: true
  gather_facts: false

  vars:
    source_directory: "c:\windows\system32\winevt\logs\"
    destination_directory: "c:\windows\temp"

  tasks:
  - name: Copy files starting with 'archive' to destination
    copy:
      src: "{{ "c:\windows\system32\winevt\logs\" }}/archive*"
      dest: "{{ "c:\windows\temp" }}/"
    register: copy_result

  - name: Delete copied files from source
    file:
      path: "{{ "c:\windows\temp" }}/archive*"
      state: absent
    when: copy_result.changed
