---
- name: Gather installed software facts from Windows servers
  hosts: all
  tasks:
    - name: Get installed software facts
      win_shell: Get-WmiObject -Class Win32_Product | Select-Object -Property Name, Version
      register: software_facts

    - name: Convert software facts to CSV format
      set_fact:
        software_csv: |
          {% for line in software_facts.stdout_lines %}
          {{ line | trim }}
          {% endfor %}

    - name: Save software facts as CSV
      copy:
        content: "{{ software_csv }}"
        dest: '\\172.16.25.23\c$\software_facts.csv'
        vars:
          ansible_become: yes
          ansible_become_method: runas
          ansible_become_user: training
          ansible_become_password: Training1!
          ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only

