---
- name: Gather installed software facts from Windows servers
  hosts: all
  tasks:
    - name: Get installed software facts
      win_shell: Get-WmiObject -Class Win32_Product | Select-Object -Property Name, Version
      register: software_facts

    - name: Display software facts
      debug:
        var: software_facts.stdout_lines
