---
- name: Copy file from network folder to C drive
  hosts: localhost
  tasks:
    - name: Decrypt credentials
      ansible.builtin.include_vars:
        file: credentials.yml
      vars:
        vault_password: "{{ vault_password }}"
    - name: Copy file
      ansible.builtin.win_copy:
        src: '\\172.16.25.22\c$\qakreport'
        dest: 'C:\'
        remote_src: yes
      become: yes
      become_user: "{{ vault_username }}"
      become_password: "{{ vault_password }}"
    - name: Run script
      ansible.builtin.win_command:
        cmd: C:\qakreport\QAK_WBC_NVE
      become: yes
      become_user: "{{ vault_username }}"
      become_password: "{{ vault_password }}"
    - name: Upload HTML file
      ansible.builtin.win_copy:
        src: 'C:\qakreport'
        dest: '\\172.16.25.22\c$\result'
      become: yes
      become_user: "{{ vault_username }}"
      become_password: "{{ vault_password }}"
