---
- name: Generate HTML report with system information for Windows servers
  hosts: all
  gather_facts: yes
  vars:
    report_file: "system_info_report.html"
    report_template: |
      <html>
        <head>
          <title>System Information Report</title>
        </head>
        <body>
          <h1>System Information Report</h1>
          <table>
            <tr>
              <th>Server Name</th>
              <th>CPU Usage</th>
              <th>Memory Usage</th>
              <th>Uptime</th>
              <th>Ping Status</th>
            </tr>
            {% for host in ansible_play_batch %}
            <tr>
              <td>{{ host }}</td>
              <td>{{ hostvars[host]['cpu_info']['cpu_usage'] }}%</td>
              <td>{{ hostvars[host]['memory_info']['memory_usage'] }}%</td>
              <td>{{ hostvars[host]['uptime_info']['uptime'] }}</td>
              <td>{% if hostvars[host]['ping_info']['ping_status'] == "reachable" %}<span style="color:green">{{ hostvars[host]['ping_info']['ping_status'] }}</span>{% else %}<span style="color:red">{{ hostvars[host]['ping_info']['ping_status'] }}</span>{% endif %}</td>
            </tr>
            {% endfor %}
          </table>
        </body>
      </html>

  tasks:
  - name: Get CPU information
    ansible.windows.win_shell: "Get-Counter '\\Processor(_Total)\\% Processor Time' | Select-Object -ExpandProperty CounterSamples | Select-Object -ExpandProperty CookedValue"
    register: cpu_info

  - name: Get memory information
    ansible.windows.win_shell: "Get-Counter '\\Memory\\% Committed Bytes In Use' | Select-Object -ExpandProperty CounterSamples | Select-Object -ExpandProperty CookedValue"
    register: memory_info

  - name: Get uptime information
    ansible.windows.win_shell: "Get-CimInstance Win32_OperatingSystem | Select-Object -ExpandProperty LastBootUpTime"
    register: uptime_info

  - name: Ping host
    ansible.windows.win_ping:
    register: ping_info

  - name: Generate HTML report
    ansible.builtin.template:
      src: /dev/null
      dest: "{{ report_file }}"
      mode: '0644'
      content: "{{ report_template }}"
