---
- name: Generate HTML report with system information for Windows servers
  hosts: windows_servers
  gather_facts: yes
  vars:
    report_file: "system_info_report.html"
    report_template: |
      <html>
        <head>
          <title>System Information Report</title>
        </head>
        <body>
          <h1>System Information Report</h1>
          <table>
            <tr>
              <th>Server Name</th>
              <th>CPU Usage</th>
              <th>Memory Usage</th>
              <th>Uptime</th>
              <th>Ping Status</th>
            </tr>
            {% for host in ansible_play_batch %}
            <tr>
              <td>{{ host }}</td>
              <td>{{ hostvars[host]['cpu_info']['stdout_lines'][0] }}%</td>
              <td>{{ hostvars[host]['memory_info']['stdout_lines'][0] }}%</td>
              <td>{{ hostvars[host]['uptime_info']['stdout_lines'][0] }}</td>
              <td>{% if hostvars[host]['ping_info']['ping'] == "pong" %}<span style="color:green">reachable</span>{% else %}<span style="color:red">unreachable</span>{% endif %}</td>
            </tr>
            {% endfor %}
          </table>
        </body>
      </html>

  tasks:
  - name: Get CPU information
    win_shell: "Get-Counter '\\Processor(_Total)\\% Processor Time' | Select-Object -ExpandProperty CounterSamples | Select-Object -ExpandProperty CookedValue"
    register: cpu_info

  - name: Get memory information
    win_shell: "Get-Counter '\\Memory\\% Committed Bytes In Use' | Select-Object -ExpandProperty CounterSamples | Select-Object -ExpandProperty CookedValue"
    register: memory_info

  - name: Get uptime information
    win_shell: "Get-CimInstance Win32_OperatingSystem | Select-Object -ExpandProperty LastBootUpTime"
    register: uptime_info

  - name: Ping host
    win_ping:
    register: ping_info

  - name: Generate HTML report
    template:
      src: /dev/null
      dest:
