---
- name: Generate server report
  hosts: all
  gather_facts: true
  tasks:
    - name: Ping server
      ping:

    - name: Get server information
      setup:
        gather_subset: "!all,!fact"

    - name: Generate report
      shell: |
        echo "Hostname,CPU Cores,Total Memory,Free Memory,% Free Space,C Drive,Uptime" > report.csv
        echo "{{ inventory_hostname }},{{ ansible_processor_vcpus }},{{ ansible_memtotal_mb }} MB,{{ ansible_memfree_mb }} MB,{{ (ansible_mounts | selectattr('mount','==','/') | map(attribute='size_available') | list | first / ansible_mounts | selectattr('mount','==','/') | map(attribute='size_total') | list | first) * 100 | round(2) }}%,{{ ansible_mounts | selectattr('mount','==','/') | map(attribute='size_free') | list | first }}/{{ ansible_mounts | selectattr('mount','==','/') | map(attribute='size_total') | list | first }},{{ ansible_uptime_seconds | int / 3600 }} hours" >> report.csv
