---
- name: Get system information from Windows host
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Get CPU information
      win_shell: |
        Get-WmiObject Win32_Processor | Select-Object -Property Name, NumberOfCores, NumberOfLogicalProcessors, MaxClockSpeed, Manufacturer
      register: cpu_info
      
    - name: Get memory information
      win_shell: |
        Get-WmiObject Win32_PhysicalMemory | Measure-Object -Property capacity -Sum | Select-Object -Property @{Name="MemoryGB";Expression={$_.Sum/1GB}}
      register: mem_info
      
    - name: Get C drive information
      win_shell: |
        Get-WmiObject Win32_LogicalDisk -Filter "DeviceID='C:'" | Select-Object -Property @{Name="Drive";Expression={$_.DeviceID}},@{Name="SizeGB";Expression={$_.Size/1GB}},@{Name="FreeSpaceGB";Expression={$_.FreeSpace/1GB}}
      register: drive_info
      
    - name: Get system uptime
      win_command: net stats srv
      register: uptime_info
      
    - name: Ping the host
      win_ping:
      register: ping_info
      
    - name: Output results in a table
      debug:
        msg: |
          System information for {{ inventory_hostname }}
          ---------------------------------------------------
          CPU:
          {% for item in cpu_info.stdout_lines %}
            {{ item }}
          {% endfor %}
          Memory:
            MemoryGB: {{ mem_info.stdout_lines[0].split(":")[1].strip() }}
          C Drive:
          {% for item in drive_info.stdout_lines %}
            {{ item }}
          {% endfor %}
          Uptime:
            {{ uptime_info.stdout_lines[3].strip() }}
          Ping:
            {{ ping_info.ping_results }}
