- name: Get server stats
  hosts: all
  gather_facts: no

  tasks:
    - name: Get CPU usage
      win_shell: Get-WmiObject win32_processor | Measure-Object -property LoadPercentage -Average | Select-Object Average
      register: cpu_usage

    - name: Get memory usage
      win_shell: Get-WmiObject win32_operatingsystem | Select-Object @{n="MemoryUsage";e={"{0:N2}%" -f ((($_.TotalVisibleMemorySize - $_.FreePhysicalMemory)*100)/ $_.TotalVisibleMemorySize)}}
      register: memory_usage

    - name: Get C drive free space
      win_shell: Get-PSDrive C | Select-Object @{n="FreeSpace(GB)";e={[math]::Round(($_.Free / 1GB), 2)}}
      register: cdrive_space

    - name: Get ping response time
      win_ping:
      register: ping_response

    - name: Get uptime
      win_shell: Get-WmiObject win32_operatingsystem | Select-Object @{n="Uptime";e={("{0} days {1}:{2}:{3}" -f $_.ConvertToDays($_.ElapsedTime), $_.ConvertToHours($_.ElapsedTime), $_.ConvertToMinutes($_.ElapsedTime), $_.ConvertToSeconds($_.ElapsedTime) % 60)}}
      register: uptime

    - name: Display results
      vars:
        data:
          - [ "{{ inventory_hostname }}", "{{ cpu_usage.stdout }}%", "{{ memory_usage.stdout.MemoryUsage }}", "{{ cdrive_space.stdout.'FreeSpace(GB)' }} GB", "{{ ping_response.ping.results[0].ping_ms }} ms", "{{ uptime.stdout.Uptime }}" ]
      run_once: true
      delegate_to: localhost
      block:
        - name: Install tabulate library
          pip:
            name: tabulate
            state: present

        - name: Display results in tabular form
          run_once: true
          delegate_to: localhost
          command: python -c "from tabulate import tabulate; print(tabulate({{ data }}, headers=['Server Name', 'CPU Usage', 'Memory Usage', 'C: Drive Free Space', 'Ping Response Time', 'Uptime']))"
