---
- name: Gather System Information
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get System Facts
      setup:
        filter: ansible_*_mb, ansible_*_cores, ansible_mounts, ansible_uptime_seconds

    - name: Ping Hosts
      ping:

    - name: Format Data
      set_fact:
        cpu: "{{ ansible_processor_cores }}"
        memory: "{{ ansible_memtotal_mb }}"
        c_drive: "{{ ansible_mounts[0].size_total | int / 1024 / 1024 }}"
        uptime: "{{ ansible_uptime_seconds }}"
        ping: "{{ 'Success' if ping.results[0].ping else 'Failure' }}"

    - name: Display Table
      debug:
        msg: |
          System Information:
          +-------+--------+---------+----------+-------+
          | Host  | CPU    | Memory  | C Drive  | Uptime | Ping  |
          +-------+--------+---------+----------+-------+
          {% for host in groups['all'] %}
          | {{ host }} | {{ hostvars[host]['cpu'] }} | {{ hostvars[host]['memory'] }} MB | {{ hostvars[host]['c_drive'] }} GB | {{ hostvars[host]['uptime'] | int / 3600 }} hours | {{ hostvars[host]['ping'] }} |
          {% endfor %}
          +-------+--------+---------+----------+-------+
