---
- name: Generate Windows server report
  hosts: all
  gather_facts: false

  vars:
    report_file: "windows_report_{{ inventory_hostname }}.csv"

  tasks:
    - name: Check server ping
      win_ping:

    - name: Get CPU and memory usage
      win_command: 'wmic cpu get loadpercentage /value && wmic os get freephysicalmemory /value'
      register: system_stats
      changed_when: false

    - name: Get % free C drive space
      win_command: 'wmic logicaldisk where "DeviceID=\'C:\'" get FreeSpace,Size /value'
      register: c_drive_stats
      changed_when: false

    - name: Get server uptime
      win_command: 'wmic os get lastbootuptime /value'
      register: uptime
      changed_when: false

    - name: Save report to CSV file
      win_shell: |
        $report_file = "{{ report_file }}"
        $system_stats = "{{ system_stats.stdout_lines }}"
        $c_drive_stats = "{{ c_drive_stats.stdout_lines }}"
        $uptime = "{{ uptime.stdout_lines }}"

        $csv = @"
          "Metric","Value"
          "CPU usage (%)",$system_stats[0]
          "Memory usage (bytes)",$system_stats[1]
          "% Free C drive space",$c_drive_stats[0]
          "C drive size (bytes)",$c_drive_stats[1]
          "Uptime",$uptime
        "@

        $csv | Out-File -FilePath $report_file -Encoding ASCII
