---
- name: Generate server report for Windows
  hosts: all
  gather_facts: true
  tasks:
    - name: Ping server
      win_ping:

    - name: Get server information
      win_command: systeminfo

    - name: Generate report
      win_shell: |
        $drive = Get-WmiObject -Class Win32_LogicalDisk -Filter "DeviceID='C:'"
        $totalSize = [math]::Round($drive.Size / 1GB,2)
        $freeSpace = [math]::Round($drive.FreeSpace / 1GB,2)
        $percentFree = [math]::Round(($freeSpace / $totalSize) * 100, 2)
        $uptime = ((Get-Date) - (gcim Win32_OperatingSystem).LastBootUpTime).TotalHours

        echo "Hostname,CPU Cores,Total Memory,Free Memory,% Free Space,C Drive,Uptime" > report.csv
        echo "{{ inventory_hostname }},{{ ansible_processor_count }},{{ ansible_memory_mb.real.total }} MB,{{ ansible_memory_mb.real.free }} MB,{{ percentFree }}%,{{ freeSpace }}/{{ totalSize }} GB,{{ uptime }} hours" >> report.csv
      args:
        executable: powershell.exe
