---
- name: Gather server information
  hosts: all
  gather_facts: false
  tasks:
    - name: Check connectivity
      win_ping:
    
    - name: Gather facts
      win_shell: |
        $cpu = Get-WmiObject win32_processor | Measure-Object -Property LoadPercentage -Average | Select-Object -ExpandProperty Average
        $mem = Get-WmiObject win32_operatingsystem | Select-Object -ExpandProperty FreePhysicalMemory
        $cdrive = Get-WmiObject win32_logicaldisk -Filter "DeviceID='C'" | Select-Object -ExpandProperty FreeSpace
        $uptime = (Get-Date) - (Get-CimInstance win32_operatingsystem | Select-Object -ExpandProperty LastBootUpTime)

        @{ CPU = $cpu; Memory = $mem; CDrive_Free_Space = $cdrive; Uptime = $uptime.TotalDays } | ConvertTo-Json
      register: server_info

    - name: Save server info to file
      win_copy:
        content: "{{ server_info.stdout }}"
        dest: "C:/ansible/server_info.json"
