---
- name: Get system information for Windows server
  hosts: all
  gather_facts: yes

  tasks:
    - name: Ping server
      win_ping:

     -name: Check CPU usage
      win_shell: "Get-WmiObject -Class Win32_Processor | Select-Object -ExpandProperty LoadPercentage"
      register: cpu_result

    - name: Get memory usage
      win_command: 'Get-WmiObject -Class Win32_OperatingSystem | Select-Object @{Label="Memory Usage (%)";Expression={"{0:N2}" -f ((($_.TotalVisibleMemorySize - $_.FreePhysicalMemory)*100)/$_.TotalVisibleMemorySize)}} | Format-Table -HideTableHeaders | Out-String'
      register: memory_output

    - name: Get uptime
      win_shell: 'Get-WmiObject -Class Win32_OperatingSystem | Select-Object @{Label="Uptime";Expression={[System.Management.ManagementDateTimeConverter]::ToTimeSpan($_.LocalDateTime.Ticks - $_.ConvertToDateTime($_.LastBootUpTime).Ticks)}} | Format-Table -HideTableHeaders | Out-String'
      register: uptime_output

    - name: Display results
      debug:
        msg: |
          CPU usage:
          {{ cpu_output.stdout }}
          Memory usage:
          {{ memory_output.stdout }}
          Uptime:
          {{ uptime_output.stdout }}
