---
- name: win_copy module demo
  hosts: all
  become: false  gather_facts: false 
 vars:
    source: "\\172.16.25.22\c$\qakreport"    
   destination: "c:\qakreport"  
 tasks:
    - name: copy report.txt
      ansible.windows.win_copy:
        src: "{{ source }}"        dest: "{{ destination }}"
