---
- name: Copy folder from remote to destination
  hosts: all
  tasks:
    - name: Copy folder
      win_copy:
        src: \\172.16.25.22\c$\qakreport
        dest: C:\
        remote_src: yes
      delegate_to: localhost
      vars:
        ansible_become_user: training
        ansible_become_password: Training1! 
