---
- name: Copy folder from remote to destination
  hosts: all
  tasks:
    - name: Copy folder
      win_copy:
        src: '\\172.16.25.22\c$\qakreport'
        dest: 'C:\'
        remote_src: yes
      vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_user: training
        ansible_become_password: Training1!
        ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
        
    - name: run script
      win_shell: C:\qakreport\QAK_WBC_NVE 
        
    - name: Upload qareport
      win_copy:
        src: "C:\qakreport\*qareport*"
        dest: '\\172.16.25.22\c$\result'
        remote_dest: yes
      vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_user: training
        ansible_become_password: Training1!
        ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only  
