---
- name: Copy a file from network, run script, and upload file to network folder
  hosts: all
    
  tasks: 
    - name: Copy file from network to C drive
      win_copy:
        src: \\172.16.25.22\c$\qakreport
        dest: C:\Temp\qakreport
        remote_src: yes
      vars:
        ansible_become_user: training
        ansible_become_password: Training1!  

    - name: run script
      win_command: C:\qakreport\QAK_WBC_NVE.cmd   

    - name: Upload file to network
      win_copy:
        src: C:\qakreport\
        dest: \\172.16.25.22\c$\result\
        remote_src: yes
      vars:
        ansible_become_user: training
        ansible_become_password: Training1!

    - name: Remove copied file
      win_file:
        path: C:\qakreport
        state: absent
