---
- name: win_copy module demo
  hosts: all
  become: false  
  gather_facts: false 
  vars:
    source: "\\172.16.25.22\c$\qakreport"    
    destination: "c:\"  
  tasks:
    - name: copy report.txt
      win_fetch:
        src: "{{ source }}"        dest: "{{ destination }}"
