---
- name: Copy folder from remote to destination
  hosts: all
  tasks:
    - name: Copy folder
      synchronize:
        src: \\172.16.25.22\c$\qakreport
        dest: C:\
      delegate_to: localhost
