---
- name: Run batch file on network share
  hosts: all
  gather_facts: false

  tasks:
    - name: Run batch file
      win_shell: '\\172.16.25.22\c$\temp\test.bat'
      register: batch_output
      become: true
      become_method: runas
      become_user: training
      become_password: Training1!
      become_flags: logon_type=new_credentials logon_flags=netcredentials_only

    - name: Display batch file output
      debug:
        var: batch_output.stdout_lines
