---
- name: Run batch file on network share
  hosts: all
  gather_facts: false

  tasks:
    - name: Run batch file
      win_shell: '\\172.16.25.22\c$\temp\test.bat'
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: training
      ansible_become_password: Training1!
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      register: batch_output

    - name: Display batch file output
      debug:
        var: batch_output.stdout_lines
